### ISSUE TITLE
Support all minors of `@babel/core`

### ISSUE THREAD

**Issue by SimenB** [nicolo-ribaudo/babel-preset-current-node-syntax#2]
Right now the minimum is `^7.8.0`, it'd be awesome to support all the way down to `^7.0.0`. You get the version passed to the preset function so we can still avoid adding too many plugins, right? I'm not sure how much more of a maintenance burden that'd add, but I'm hoping it's feasible 😀 

If we do this, I can add this preset to Jest without waiting for a new major (our current peer dependency is `^7.0.0`)

**Comment by nicolo-ribaudo** [comment]
Adding too many syntax plugins shouldn't hurt, because most of the time is spent while transforming the AST rather than when initializing plugins (syntax plugins only run during initialization).

**Comment by nicolo-ribaudo** [comment]
Added in 155d2ccae85347e79f1978a489ea9dd329da3a4d. I tested it locally with different node versions and it seems to work, but I want to wait for GH actions to be up again before releasing.

**Comment by SimenB** [comment]
Wonderful, thanks!

**Comment by SimenB** [comment]
Ping me when released? 🙂

**Comment by nicolo-ribaudo** [comment]
@SimenB Published as 0.1.1
